catelog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('loanedbooks/', views.LoanedBooksListView.as_view(), name='loaned-out'),
    path('book/<uuid:pk>/renew', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('bookinstance/<int:pk>/create/', views.BookInstanceCreate.as_view(), name='bookinstance-create'), # pk for book
    path('bookinstance/<str:pk>/update/', views.BookInstanceUpdate.as_view(), name='bookinstance-update'),
    path('bookinstance/<str:pk>/delete/', views.BookInstanceDelete.as_view(), name='bookinstance-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catelog application
from django.urls import include

urlpatterns += [
    path('catelog/', include('catelog.urls')),
]


# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catelog/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
   path('accounts/', include('django.contrib.auth.urls')),
]

catelog/models.py
from django.db import models
from django.conf import settings
from datetime import date

# Create your models here.
from django.urls import reverse # Used in get_absolute_url() to get URL for specified ID
from django.db.models import UniqueConstraint # Constrains fields to unique values
from django.db.models.functions import Lower # Returns lower cased value of field

class Genre(models.Model):
    """Model representing af books genre."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='genre_name_case_insensitive_unique',
                violation_error_message=("Genre already exists (case insensitive match)"),
            ),
        ]

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    
    author = models.ForeignKey(
        'Author',
        on_delete=models.RESTRICT,
        null=True
    )
    # Foreign Key used because book can only have one author, but authors can 
    # have multiple books. Author as a string rather than object because it 
    # hasn't been declared yet in file.

    summary = models.TextField(
        max_length=1000,
        help_text="Enter a brief description of the book",
        null=True,
    )

    isbn = models.CharField(
        'ISBN',
        max_length=13,
        unique=True,
        null=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn''">ISBN number</a>'
    )

    # ManyToManyField used because genre can contain many books. Books can 
    # cover many genres. Genre class has already been defined so we can specify
    # the object above.

    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    language = models.ForeignKey(
        'Language', 
        on_delete=models.SET_NULL,
        # on_delete=models.RESTRICT,
        null=True
    )

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        genreText = ', '.join(genre.name for genre in self.genre.all()[:3])
        numGenres = self.genre.all().count()
        if numGenres > 3:
            genreText = genreText + f' (+ {numGenres - 3} more)'
        return genreText
    
    display_genre.short_description = 'Genre'

import uuid # Required for unique book instances

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed
       from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library"
    )

    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, help_text="A date between now and 4 weeks.")
    # due_back = models.DateField(null=True, blank=True, help_text="A date between now and 4 weeks.", verbose_name="Renewal date")

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, \
                                 on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ['due_back']
        # Defining permissions is done on the model class Meta section, using 
        # the permissions field     
        permissions = [("can_mark_returned", "Set book as returned"),]

    def __str__(self):
        return f'{self.id} ({self.book.title if self.book else "No book"})'
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this bookinstance."""
        return reverse('book-detail', args=[str(self.book.id)])
    
class Author(models.Model):
    """Model representing an Author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    about = models.TextField(
        max_length=1000,
        help_text="Enter a brief description of the Author",
        null=True,
    )

    class Meta:
        ordering = ['last_name', 'first_name']
        # permissions = [("can_create_author", "Can create author")]

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
class Language(models.Model):
    """Model representing a book language (e.g. English, French, Japanese, etc.)."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)"
    )

    def get_absolute_url(self):
        """Returns the URL to access a particular language instance."""
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the model language"""
        return self.name
    
    class Meta:
        # ordering = ['name',],
        constraints = [
            UniqueConstraint(
                Lower('name'),
                name='language_name_case_insensitive_unique',
                violation_error_message="Language alreade exists (case insensitive match)"
            ),
        ]

catelog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from catelog.models import BookInstance


class RenewBookForm(forms.Form):
    """Form for renewing a book."""

    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        """Validate the renewal date."""
        data = self.cleaned_data["renewal_date"]

        # Check if a date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+4 weeks from today)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))

        # Remember to always return the cleaned data
        return data


class RenewBookModelForm(forms.ModelForm):
    """Form for renewing a book."""

    def clean_due_back(self):
        """Validate the due back date."""
        data = self.cleaned_data["due_back"]

        # Check if a date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+4 weeks from today)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))

        # Remember to always return the cleaned data
        return data

    class Meta:
        """Meta class for the RenewBookModelForm."""
        model = BookInstance
        fields = ["due_back"]
        # labels = {"due_back": _("Renewal date")}
        help_texts = {
            "due_back": _("Enter a date between now and 4 weeks (default 3).")
        }


class BookInstanceUpdateForm(forms.ModelForm):
    """Form for updating a BookInstance with read-only id field."""
    
    class Meta:
        model = BookInstance
        # fields = ["id", "book", "imprint", "due_back", "status", "borrower"]
        fields = ["imprint", "due_back", "status", "borrower"]
    
    # ADA, 2.8.: dette virkede ikke da den ikke kunne gemme opdateret værdier.
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
        
    #     # Make the id field read-only and disabled
    #     if self.instance and self.instance.pk:
    #         self.fields['id'].widget.attrs.update({
    #             'readonly': 'readonly',
    #             'disabled': 'disabled',
    #             'style': 
    #                 'background-color: #f0f0f0;' +
    #                 'width: 100%;' +
    #                 'text-align: center;'
    #         })

catelog/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block title %}
      <title>Local Library</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav custom-list">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'books' %}">All books</a></li>
              <li class="mb-5"><a href="{% url 'authors' %}">All authors</a></li>
              <!-- <hr> -->
              {% if user.is_authenticated %}
                <li class="h6">User Info:</li>
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
                <li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                  </form>
                </li>
                <hr class="mb-5">
                <li class="h6">Staff</li>
                {% if user.is_staff %}
                  <li><a href="{% url 'loaned-out' %}">All borrowed</a></li>
                  {% if perms.catelog.add_author %}
                    <li><a href="{% url 'author-create' %}">Create author</a></li>
                  {% endif %}
                  {% if perms.catelog.add_book %}
                    <li><a href="{% url 'book-create' %}">Create book</a></li>
                  {% endif %}
                {% endif %}
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
              {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
              <div class="pagination">
                <span class="page-links">
                  {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number}}">
                      Previous
                    </a>
                  {% endif %}
                  <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
                  </span>
                  {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number}}">
                      Next
                    </a>
                  {% endif %}
                </span>
              </div>
            {% endif %}
          {% endblock%}
        </div>
      </div>
    </div>
  </body>
</html>

catelog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
    <title>myLocalLib</title>
{% endblock %}

{% block content %}

<h1>Local Library Home</h1>
<p>
    Welcome to LocalLibrary, a website developed by
    <em>Andreas Dal</em>
</p>
<!-- <p>You are logged in as: <strong>{{ user }}</strong></p> -->
<h2>Dynamic Content</h2>
<p>The library has the following record counts:</p>
<ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Books containing the word "the":</strong> {{ num_books_with_the }}</li>
    <li><strong>Genres containing 'a': </strong> {{ num_genres_with_a }}</li>
</ul>

<p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize}}.
</p>

{% endblock %}